import Head from "next/head";
import React from "react";
import { useRouter } from "next/router";
import axios from "axios";
import MainLayout from "../../../layouts/MainLayout";
import { useHasHydrated } from "../../../utils/useHydrated";
import Success from "../../../components/icons/Success";
import Button from "../../../components/Button";
import Link from "next/link";
import { useCartStore } from "../../../utils/store";

export default function CheckoutSuccess() {
  const [loading, setLoading] = React.useState(false);
  const [data, setData] = React.useState<any>();
  const hasHydrated = useHasHydrated();
  const router = useRouter();
  const { clearCart } = useCartStore();

  React.useEffect(() => {
    setLoading(true);
    // If we have a session ID, we can make a call to the backend
    if (router.query.session_id) {
      axios
        .get(`http://localhost:3000/checkout/${router.query.session_id}`)
        .then((res) => {
          setData(res.data);
          // TODO: Ensure that this only runs if your checkout succeeds, not when you hit this page
          clearCart();
        })
        .catch((err) => {
          console.log(err);
          // router.push("/grants");
        })
        .finally(() => setLoading(false));
    }
    // if (hasHydrated && !loading && !router.query.session_id) {
    //   router.push("/grants");
    // }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [router.query, hasHydrated, router]);

  return (
    <div>
      <Head>
        <title>Donation Successful</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        {hasHydrated && data && !loading && (
          <div className="flex flex-col w-full min-h-screen h-full items-center justify-center text-center">
            <Success className="fill-sg-success mb-6" />
            <h1 className="font-bold text-3xl mb-3">Congratulations</h1>
            <p className="text-2xl">Your donations have been processed!</p>
            <p className="font-bold text-3xl max-w-2xl my-16">
              Your donation of $
              {data.donated.toLocaleString("en-US", {
                minimumFractionDigits: 2,
                maximumFractionDigits: 2,
              })}{" "}
              USD is matched with an additional{" "}
              <b className="text-sg-success">
                $
                {data.matched.toLocaleString("en-US", {
                  minimumFractionDigits: 2,
                  maximumFractionDigits: 2,
                })}
              </b>{" "}
              going to {data.numberOfGrants} separate grants!
            </p>
            <div className="flex flex-row gap-x-8">
              <Button>Share on Twitter</Button>
              <Button>Share on Facebook</Button>
              <Button>Copy Link</Button>
            </div>
            <Link href="/grants">
              <Button className="mt-6" style="secondary">
                Back To Grants
              </Button>
            </Link>
          </div>
        )}
      </MainLayout>
    </div>
  );
}
