import Head from "next/head";
import React from "react";
import { useRouter } from "next/router";
import axios from "../../../utils/axios";
import MainLayout from "../../../layouts/MainLayout";
import { useHasHydrated } from "../../../utils/useHydrated";
import Success from "../../../components/icons/Success";
import Button from "../../../components/Button";
import Link from "next/link";
import { useGrantCartStore } from "../../../utils/store";
import Image from "next/image";
import Copy from "../../../components/icons/Copy";
import { FacebookShareButton, TwitterShareButton } from "react-share";

export default function CheckoutSuccess() {
  const [loading, setLoading] = React.useState(false);
  const [data, setData] = React.useState<any>();
  const hasHydrated = useHasHydrated();
  const router = useRouter();
  const { clearCart } = useGrantCartStore();
  const shareInformation = React.useMemo(() => {
    if (typeof window !== undefined && data) {
      return {
        url: window.location.href,
        message: `I've just donated $${data.donated.toLocaleString("en-US", {
          minimumFractionDigits: 2,
          maximumFractionDigits: 2,
        })} to ${data.numberOfGrants} grants! Check it out here!🥳\n`,
      };
    }
  }, [data]);

  React.useEffect(() => {
    setLoading(true);
    // If we have a session ID, we can make a call to the backend
    if (router.query.session_id) {
      axios
        .get(`/checkout/${router.query.session_id}`)
        .then((res) => {
          setData(res.data);
          // TODO: Ensure that this only runs if your checkout succeeds, not when you hit this page
          clearCart();
        })
        .catch((err) => {
          console.log(err);
          // router.push("/grants");
        })
        .finally(() => setLoading(false));
    }
    // if (hasHydrated && !loading && !router.query.session_id) {
    //   router.push("/grants");
    // }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [router.query, hasHydrated, router]);

  return (
    <div>
      <Head>
        <title>Donation Successful</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout className="h-full min-h-screen items-center justify-center bg-sg-gradient">
        <Image
          src={"/assets/texture.svg"}
          alt=""
          fill
          className="object-cover pointer-events-none"
        />
        {hasHydrated && data && !loading && (
          <div className="flex flex-col w-full min-h-screen h-full items-center justify-center text-center">
            <Success className="fill-sg-success mb-6" />
            <h1 className="font-bold text-3xl mb-3">Congratulations!</h1>
            <p className="text-2xl max-w-2xl mt-2 mb-10">
              Your{" "}
              <b>
                $
                {data.donated.toLocaleString("en-US", {
                  minimumFractionDigits: 2,
                  maximumFractionDigits: 2,
                })}
              </b>{" "}
              donation has been processed! The estimated matching amount is{" "}
              <b>
                $
                {data.matched.toLocaleString("en-US", {
                  minimumFractionDigits: 2,
                  maximumFractionDigits: 2,
                })}
              </b>
              .
            </p>
            {shareInformation && (
              <>
                <Button
                  style="ghost"
                  onClick={() => {
                    navigator.clipboard.writeText(window.location.href);
                  }}
                  className="mb-5"
                >
                  <Copy className="stroke-sg-secondary mr-2" />
                  Copy link
                </Button>
                <div className="flex flex-row items-center justify-center w-full gap-6">
                  <TwitterShareButton
                    url={shareInformation.url}
                    title={shareInformation.message}
                  >
                    <Button style="outline">Share on Twitter</Button>
                  </TwitterShareButton>
                  <FacebookShareButton
                    url={shareInformation.url}
                    quote={shareInformation.message}
                  >
                    <Button style="outline">Share on Facebook</Button>
                  </FacebookShareButton>
                </div>
              </>
            )}

            <Link href="/grants">
              <Button className="mt-6" style="secondary">
                Back To Grants
              </Button>
            </Link>
          </div>
        )}
      </MainLayout>
    </div>
  );
}
