FROM node:18-alpine

# For compatibility with M1 Macs
RUN apk update && \
    apk add procps && \
    apk add openssl && \
    apk add libc6-compat

RUN npm i -g pnpm

# Create app directory
WORKDIR /app

ARG FRONTEND_PORT

RUN npx prisma generate

CMD pnpm dev -p $FRONTEND_PORT