FROM node:18-slim

# For compatibility with M1 Macs
RUN apt-get update && \
    apt-get install -y procps && \
    apt-get install -y openssl && \
    apt-get install -y libc6 && \
    apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

# Create app directory
WORKDIR /app

# npm install files
COPY package*.json ./
COPY prisma ./prisma/

# Install app dependencies
RUN npm install

CMD npm run start:dev