import Head from "next/head";
import React from "react";
import { useRouter } from "next/router";
import { toast } from "react-toastify";
import axios from "axios";

const defaultData = {
  donated: 0,
  matched: 0,
  numberOfGrants: 0,
};

export default function Success() {
  const [data, setData] = React.useState(defaultData);
  const router = useRouter();

  React.useEffect(() => {
    // If we have a session ID, we can make a call to the backend
    if (router.query.session_id) {
      console.log(router.query.session_id);
      axios
        .get(`http://localhost:3000/checkout/${router.query.session_id}`)
        .then((res) => {
          setData(res.data);
        })
        .catch((err) => {
          console.log(err);
          toast.error("Unable to retrieve checkout data");
        });
    }
  }, [router.query]);

  return (
    <div>
      <Head>
        <title>Donation Successful</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Your donation of ${data.donated} USD is matched with an additional $
        {data.matched} going to {data.numberOfGrants} separate grants!
      </main>
    </div>
  );
}
